// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nova.Maestros.Infrastructure;

#nullable disable

namespace Nova.Maestros.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MaestrosDbContext))]
    [Migration("20260611002926_AddEmpleado")]
    partial class AddEmpleado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("maes")
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nova.Maestros.Domain.AmbitoFeriado", b =>
                {
                    b.Property<Guid>("IdFeriado")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_feriado");

                    b.Property<string>("TipoAmbito")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("tipo_ambito");

                    b.Property<Guid>("IdAmbito")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_ambito");

                    b.HasKey("IdFeriado", "TipoAmbito", "IdAmbito");

                    b.ToTable("ambito_feriado", "maes");
                });

            modelBuilder.Entity("Nova.Maestros.Domain.AuditoriaMaestros", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_log");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)")
                        .HasColumnName("accion");

                    b.Property<string>("Elemento")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("elemento");

                    b.Property<DateTimeOffset>("FechaHora")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("fecha_hora");

                    b.Property<Guid>("IdActor")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_actor");

                    b.Property<string>("Justificacion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("justificacion");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("valor_anterior");

                    b.Property<string>("ValorNuevo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("valor_nuevo");

                    b.Property<DateOnly?>("VigenciaDesde")
                        .HasColumnType("date")
                        .HasColumnName("vigencia_desde");

                    b.HasKey("Id");

                    b.HasIndex("Elemento", "FechaHora")
                        .HasDatabaseName("idx_auditoria_config_elemento_fecha");

                    b.ToTable("auditoria_config", "maes");
                });

            modelBuilder.Entity("Nova.Maestros.Domain.Empleado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_empleado");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("cargo");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("categoria");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("codigo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("estado");

                    b.Property<string>("IdEmpresa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("id_empresa");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("origen");

                    b.Property<DateTimeOffset?>("RmsSyncAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("rms_sync_at");

                    b.Property<string>("Tienda")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("tienda");

                    b.Property<string>("Zona")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("zona");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("uk_empleado_codigo");

                    b.HasIndex("IdEmpresa", "Categoria", "Estado")
                        .HasDatabaseName("idx_empleado_empresa_categoria_estado");

                    b.ToTable("empleado", "maes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000001"),
                            Cargo = "Gerente Titular",
                            Categoria = "GtAsesores",
                            Codigo = "E-0001",
                            Estado = "Activo",
                            IdEmpresa = "CADENA",
                            NombreCompleto = "Ana Torres",
                            Origen = "Rms",
                            Tienda = "Mega Plaza",
                            Zona = "Zona Lima Norte"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000002"),
                            Cargo = "Asesor",
                            Categoria = "GtAsesores",
                            Codigo = "E-0002",
                            Estado = "Activo",
                            IdEmpresa = "CADENA",
                            NombreCompleto = "Luis Ramos",
                            Origen = "Rms",
                            Tienda = "Mega Plaza",
                            Zona = "Zona Lima Norte"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000003"),
                            Cargo = "Asesor Senior",
                            Categoria = "Seniors",
                            Codigo = "E-0003",
                            Estado = "Activo",
                            IdEmpresa = "CADENA",
                            NombreCompleto = "María Díaz",
                            Origen = "Rms",
                            Tienda = "Mega Plaza",
                            Zona = "Zona Lima Norte"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000004"),
                            Cargo = "Asesor",
                            Categoria = "GtAsesores",
                            Codigo = "E-0004",
                            Estado = "Vacaciones",
                            IdEmpresa = "CADENA",
                            NombreCompleto = "Jorge Vega",
                            Origen = "Rms",
                            Tienda = "Plaza Norte",
                            Zona = "Zona Lima Norte"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000005"),
                            Cargo = "Secretaria",
                            Categoria = "Secretarias",
                            Codigo = "E-0005",
                            Estado = "Activo",
                            IdEmpresa = "CADENA",
                            NombreCompleto = "Sofía Núñez",
                            Origen = "Rms",
                            Tienda = "Plaza Norte",
                            Zona = "Zona Lima Norte"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000006"),
                            Cargo = "Asesor Senior",
                            Categoria = "Seniors",
                            Codigo = "E-0006",
                            Estado = "Activo",
                            IdEmpresa = "CADENA",
                            NombreCompleto = "Carlos Pérez",
                            Origen = "Rms",
                            Tienda = "Jockey Plaza",
                            Zona = "Zona Lima Sur"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000007"),
                            Cargo = "Asesor",
                            Categoria = "GtAsesores",
                            Codigo = "E-0007",
                            Estado = "Descanso",
                            IdEmpresa = "CADENA",
                            NombreCompleto = "Lucía Flores",
                            Origen = "Rms",
                            Tienda = "Jockey Plaza",
                            Zona = "Zona Lima Sur"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000008"),
                            Cargo = "Auxiliar",
                            Categoria = "Auxiliares",
                            Codigo = "E-0008",
                            Estado = "Activo",
                            IdEmpresa = "CADENA",
                            NombreCompleto = "Diego Salas",
                            Origen = "Rms",
                            Tienda = "Jockey Plaza",
                            Zona = "Zona Lima Sur"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-000000000009"),
                            Cargo = "Sastre",
                            Categoria = "Sastres",
                            Codigo = "E-0009",
                            Estado = "Activo",
                            IdEmpresa = "LUKERS",
                            NombreCompleto = "Rosa Campos",
                            Origen = "Rms",
                            Tienda = "Jockey Plaza",
                            Zona = "Zona Lima Sur"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-00000000000a"),
                            Cargo = "Asesor",
                            Categoria = "GtAsesores",
                            Codigo = "E-0010",
                            Estado = "Activo",
                            IdEmpresa = "LUKERS",
                            NombreCompleto = "Pedro Quispe",
                            Origen = "Rms",
                            Tienda = "Plaza Norte",
                            Zona = "Zona Lima Norte"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-00000000000b"),
                            Cargo = "Asesor Senior",
                            Categoria = "Seniors",
                            Codigo = "E-0011",
                            Estado = "Licencia",
                            IdEmpresa = "LUKERS",
                            NombreCompleto = "Elena Ríos",
                            Origen = "Rms",
                            Tienda = "Plaza Norte",
                            Zona = "Zona Lima Norte"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-0000-0000-00000000000c"),
                            Cargo = "Auxiliar",
                            Categoria = "Auxiliares",
                            Codigo = "E-0012",
                            Estado = "Activo",
                            IdEmpresa = "LUKERS",
                            NombreCompleto = "Marco Aguilar",
                            Origen = "Rms",
                            Tienda = "Mega Plaza",
                            Zona = "Zona Lima Norte"
                        });
                });

            modelBuilder.Entity("Nova.Maestros.Domain.Empresa", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("id_empresa");

                    b.Property<string>("DiaInicioSemana")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("dia_inicio_semana");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("estado");

                    b.Property<bool>("ExisteCoberturaTipoVenta")
                        .HasColumnType("bit")
                        .HasColumnName("existe_cobertura_tipo_venta");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("nombre");

                    b.HasKey("Codigo");

                    b.ToTable("empresa", "maes");

                    b.HasData(
                        new
                        {
                            Codigo = "CADENA",
                            DiaInicioSemana = "Domingo",
                            Estado = "Vigente",
                            ExisteCoberturaTipoVenta = false,
                            Nombre = "Cadena"
                        },
                        new
                        {
                            Codigo = "LUKERS",
                            DiaInicioSemana = "Domingo",
                            Estado = "Vigente",
                            ExisteCoberturaTipoVenta = true,
                            Nombre = "Lukers"
                        });
                });

            modelBuilder.Entity("Nova.Maestros.Domain.Feriado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_feriado");

                    b.Property<string>("Alcance")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("alcance");

                    b.Property<bool>("Compensable")
                        .HasColumnType("bit")
                        .HasColumnName("compensable");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("descripcion");

                    b.Property<string>("EmpresasAplicables")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("empresas_aplicables");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("origen");

                    b.Property<DateOnly>("VigenciaDesde")
                        .HasColumnType("date")
                        .HasColumnName("vigencia_desde");

                    b.Property<DateOnly?>("VigenciaHasta")
                        .HasColumnType("date")
                        .HasColumnName("vigencia_hasta");

                    b.HasKey("Id");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("idx_feriado_fecha");

                    b.ToTable("feriado", "maes");
                });

            modelBuilder.Entity("Nova.Maestros.Domain.Parametro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_parametro");

                    b.Property<string>("Ambito")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ambito");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("clave");

                    b.Property<string>("CriticidadConsumo")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("criticidad_consumo");

                    b.Property<bool>("EsImpactoNegocio")
                        .HasColumnType("bit")
                        .HasColumnName("es_impacto_negocio");

                    b.Property<string>("Flujo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("flujo");

                    b.Property<string>("IdAmbito")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("id_ambito");

                    b.Property<string>("IdEmpresa")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("id_empresa");

                    b.Property<string>("Justificacion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("justificacion");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("modulo");

                    b.Property<string>("Nivel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("nivel");

                    b.Property<string>("NombreParametro")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("nombre_parametro");

                    b.Property<string>("TipoDato")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("tipo_dato");

                    b.Property<string>("Unidad")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("unidad");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("valor");

                    b.Property<DateOnly>("VigenciaDesde")
                        .HasColumnType("date")
                        .HasColumnName("vigencia_desde");

                    b.Property<DateOnly?>("VigenciaHasta")
                        .HasColumnType("date")
                        .HasColumnName("vigencia_hasta");

                    b.HasKey("Id");

                    b.HasIndex("Clave", "IdEmpresa", "IdAmbito", "VigenciaDesde")
                        .HasDatabaseName("idx_parametro_clave_ambito_vigencia");

                    b.ToTable("parametro", "maes");
                });

            modelBuilder.Entity("Nova.Maestros.Domain.Permiso", b =>
                {
                    b.Property<string>("Clave")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("clave");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("accion");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("modulo");

                    b.HasKey("Clave");

                    b.ToTable("permiso", "maes");

                    b.HasData(
                        new
                        {
                            Clave = "SEGU.USUARIO.CREAR",
                            Accion = "Crear",
                            Modulo = "Seguridad"
                        },
                        new
                        {
                            Clave = "SEGU.USUARIO.LEER",
                            Accion = "Leer",
                            Modulo = "Seguridad"
                        },
                        new
                        {
                            Clave = "SEGU.ROL.CONFIGURAR",
                            Accion = "Configurar",
                            Modulo = "Seguridad"
                        },
                        new
                        {
                            Clave = "MAES.PARAMETRO.CONFIGURAR",
                            Accion = "Configurar",
                            Modulo = "Maestros"
                        },
                        new
                        {
                            Clave = "MAES.CATALOGO.LEER",
                            Accion = "Leer",
                            Modulo = "Maestros"
                        },
                        new
                        {
                            Clave = "APRO.TAREA.APROBAR",
                            Accion = "Aprobar",
                            Modulo = "Aprobaciones"
                        },
                        new
                        {
                            Clave = "ROL.ROL.ENVIAR",
                            Accion = "Enviar",
                            Modulo = "Rol"
                        },
                        new
                        {
                            Clave = "ROL.ROL.LEER",
                            Accion = "Leer",
                            Modulo = "Rol"
                        },
                        new
                        {
                            Clave = "MARC.MARCACION.LEER",
                            Accion = "Leer",
                            Modulo = "Marc"
                        });
                });

            modelBuilder.Entity("Nova.Maestros.Domain.Puesto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_puesto");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("codigo");

                    b.Property<bool>("GeneraRatiosSenior")
                        .HasColumnType("bit")
                        .HasColumnName("genera_ratios_senior");

                    b.Property<bool>("HabilitadoSenior")
                        .HasColumnType("bit")
                        .HasColumnName("habilitado_senior");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("nombre");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("origen");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("uk_puesto_codigo");

                    b.ToTable("puesto", "maes");
                });

            modelBuilder.Entity("Nova.Maestros.Domain.Rol", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("id_rol");

                    b.Property<string>("AmbitoPermitido")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ambito_permitido");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("estado");

                    b.Property<int>("NivelAutoridad")
                        .HasColumnType("int")
                        .HasColumnName("nivel_autoridad");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("nombre");

                    b.HasKey("Codigo");

                    b.ToTable("rol", "maes");

                    b.HasData(
                        new
                        {
                            Codigo = "R-EMP",
                            AmbitoPermitido = "Tienda",
                            Estado = "Vigente",
                            NivelAutoridad = 10,
                            Nombre = "Empleado"
                        },
                        new
                        {
                            Codigo = "R-SENIOR",
                            AmbitoPermitido = "Tienda",
                            Estado = "Vigente",
                            NivelAutoridad = 20,
                            Nombre = "Senior"
                        },
                        new
                        {
                            Codigo = "R-GT",
                            AmbitoPermitido = "Tienda",
                            Estado = "Vigente",
                            NivelAutoridad = 30,
                            Nombre = "Gerente Titular"
                        },
                        new
                        {
                            Codigo = "R-AR",
                            AmbitoPermitido = "Central",
                            Estado = "Vigente",
                            NivelAutoridad = 35,
                            Nombre = "Administración Retail"
                        },
                        new
                        {
                            Codigo = "R-AV",
                            AmbitoPermitido = "Central",
                            Estado = "Vigente",
                            NivelAutoridad = 40,
                            Nombre = "Administración de Ventas"
                        },
                        new
                        {
                            Codigo = "R-GZ",
                            AmbitoPermitido = "Zona",
                            Estado = "Vigente",
                            NivelAutoridad = 50,
                            Nombre = "Gerente de Zona"
                        },
                        new
                        {
                            Codigo = "R-GG-SUP",
                            AmbitoPermitido = "Central",
                            Estado = "Vigente",
                            NivelAutoridad = 60,
                            Nombre = "GG Suplente"
                        },
                        new
                        {
                            Codigo = "R-GG",
                            AmbitoPermitido = "Central",
                            Estado = "Vigente",
                            NivelAutoridad = 70,
                            Nombre = "Gerencia General"
                        },
                        new
                        {
                            Codigo = "R-BIEN",
                            AmbitoPermitido = "Central",
                            Estado = "Vigente",
                            NivelAutoridad = 70,
                            Nombre = "Bienestar"
                        },
                        new
                        {
                            Codigo = "R-ADM",
                            AmbitoPermitido = "Central",
                            Estado = "Vigente",
                            NivelAutoridad = 100,
                            Nombre = "Administrador del Sistema"
                        });
                });

            modelBuilder.Entity("Nova.Maestros.Domain.RolPermiso", b =>
                {
                    b.Property<string>("IdRol")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("id_rol");

                    b.Property<string>("ClavePermiso")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("clave_permiso");

                    b.HasKey("IdRol", "ClavePermiso");

                    b.HasIndex("ClavePermiso");

                    b.ToTable("rol_permiso", "maes");

                    b.HasData(
                        new
                        {
                            IdRol = "R-ADM",
                            ClavePermiso = "SEGU.USUARIO.CREAR"
                        },
                        new
                        {
                            IdRol = "R-ADM",
                            ClavePermiso = "SEGU.USUARIO.LEER"
                        },
                        new
                        {
                            IdRol = "R-ADM",
                            ClavePermiso = "SEGU.ROL.CONFIGURAR"
                        },
                        new
                        {
                            IdRol = "R-ADM",
                            ClavePermiso = "MAES.PARAMETRO.CONFIGURAR"
                        },
                        new
                        {
                            IdRol = "R-ADM",
                            ClavePermiso = "MAES.CATALOGO.LEER"
                        },
                        new
                        {
                            IdRol = "R-ADM",
                            ClavePermiso = "APRO.TAREA.APROBAR"
                        },
                        new
                        {
                            IdRol = "R-GG",
                            ClavePermiso = "ROL.ROL.ENVIAR"
                        },
                        new
                        {
                            IdRol = "R-GG",
                            ClavePermiso = "ROL.ROL.LEER"
                        },
                        new
                        {
                            IdRol = "R-GG",
                            ClavePermiso = "APRO.TAREA.APROBAR"
                        },
                        new
                        {
                            IdRol = "R-GG",
                            ClavePermiso = "MAES.CATALOGO.LEER"
                        },
                        new
                        {
                            IdRol = "R-GZ",
                            ClavePermiso = "ROL.ROL.ENVIAR"
                        },
                        new
                        {
                            IdRol = "R-GZ",
                            ClavePermiso = "ROL.ROL.LEER"
                        },
                        new
                        {
                            IdRol = "R-GZ",
                            ClavePermiso = "APRO.TAREA.APROBAR"
                        },
                        new
                        {
                            IdRol = "R-GT",
                            ClavePermiso = "ROL.ROL.LEER"
                        },
                        new
                        {
                            IdRol = "R-GT",
                            ClavePermiso = "MARC.MARCACION.LEER"
                        },
                        new
                        {
                            IdRol = "R-EMP",
                            ClavePermiso = "MARC.MARCACION.LEER"
                        });
                });

            modelBuilder.Entity("Nova.Maestros.Domain.SemanaCampania", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_semana");

                    b.Property<DateOnly>("Desde")
                        .HasColumnType("date")
                        .HasColumnName("desde");

                    b.Property<DateOnly>("Hasta")
                        .HasColumnType("date")
                        .HasColumnName("hasta");

                    b.Property<string>("IdEmpresa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("id_empresa");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa", "Desde")
                        .HasDatabaseName("idx_campania_empresa_desde");

                    b.ToTable("semana_campania", "maes");
                });

            modelBuilder.Entity("Nova.Maestros.Domain.Tienda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_tienda");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("codigo");

                    b.Property<int>("DotacionMinimaAsesores")
                        .HasColumnType("int")
                        .HasColumnName("dotacion_minima_asesores");

                    b.Property<string>("EstadoOperativo")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("estado_operativo");

                    b.Property<DateOnly?>("FechaVigenciaDotacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_vigencia_dotacion");

                    b.Property<string>("IdEmpresa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("id_empresa");

                    b.Property<Guid?>("IdZona")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_zona");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("nombre");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("origen");

                    b.Property<DateTimeOffset?>("RmsSyncAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("rms_sync_at");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("ubicacion");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("uk_tienda_codigo");

                    b.HasIndex("IdEmpresa", "EstadoOperativo")
                        .HasDatabaseName("idx_tienda_empresa_estado");

                    b.ToTable("tienda", "maes");
                });

            modelBuilder.Entity("Nova.Maestros.Domain.Zona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_zona");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("estado");

                    b.Property<string>("IdEmpresa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("id_empresa");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa")
                        .HasDatabaseName("idx_zona_empresa");

                    b.ToTable("zona", "maes");
                });

            modelBuilder.Entity("Nova.Maestros.Domain.AmbitoFeriado", b =>
                {
                    b.HasOne("Nova.Maestros.Domain.Feriado", null)
                        .WithMany("Ambitos")
                        .HasForeignKey("IdFeriado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nova.Maestros.Domain.RolPermiso", b =>
                {
                    b.HasOne("Nova.Maestros.Domain.Permiso", null)
                        .WithMany()
                        .HasForeignKey("ClavePermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nova.Maestros.Domain.Rol", null)
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nova.Maestros.Domain.Feriado", b =>
                {
                    b.Navigation("Ambitos");
                });
#pragma warning restore 612, 618
        }
    }
}
