// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nova.Maestros.Infrastructure;

#nullable disable

namespace Nova.Maestros.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MaestrosDbContext))]
    partial class MaestrosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("maes")
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nova.Maestros.Domain.AmbitoFeriado", b =>
                {
                    b.Property<Guid>("IdFeriado")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_feriado");

                    b.Property<string>("TipoAmbito")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("tipo_ambito");

                    b.Property<Guid>("IdAmbito")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_ambito");

                    b.HasKey("IdFeriado", "TipoAmbito", "IdAmbito");

                    b.ToTable("ambito_feriado", "maes");
                });

            modelBuilder.Entity("Nova.Maestros.Domain.AuditoriaMaestros", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_log");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)")
                        .HasColumnName("accion");

                    b.Property<string>("Elemento")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("elemento");

                    b.Property<DateTimeOffset>("FechaHora")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("fecha_hora");

                    b.Property<Guid>("IdActor")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_actor");

                    b.Property<string>("Justificacion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("justificacion");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("valor_anterior");

                    b.Property<string>("ValorNuevo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("valor_nuevo");

                    b.Property<DateOnly?>("VigenciaDesde")
                        .HasColumnType("date")
                        .HasColumnName("vigencia_desde");

                    b.HasKey("Id");

                    b.HasIndex("Elemento", "FechaHora")
                        .HasDatabaseName("idx_auditoria_config_elemento_fecha");

                    b.ToTable("auditoria_config", "maes");
                });

            modelBuilder.Entity("Nova.Maestros.Domain.Empresa", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("id_empresa");

                    b.Property<string>("DiaInicioSemana")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("dia_inicio_semana");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("estado");

                    b.Property<bool>("ExisteCoberturaTipoVenta")
                        .HasColumnType("bit")
                        .HasColumnName("existe_cobertura_tipo_venta");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("nombre");

                    b.HasKey("Codigo");

                    b.ToTable("empresa", "maes");
                });

            modelBuilder.Entity("Nova.Maestros.Domain.Feriado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_feriado");

                    b.Property<string>("Alcance")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("alcance");

                    b.Property<bool>("Compensable")
                        .HasColumnType("bit")
                        .HasColumnName("compensable");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("descripcion");

                    b.Property<string>("EmpresasAplicables")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("empresas_aplicables");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("origen");

                    b.Property<DateOnly>("VigenciaDesde")
                        .HasColumnType("date")
                        .HasColumnName("vigencia_desde");

                    b.Property<DateOnly?>("VigenciaHasta")
                        .HasColumnType("date")
                        .HasColumnName("vigencia_hasta");

                    b.HasKey("Id");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("idx_feriado_fecha");

                    b.ToTable("feriado", "maes");
                });

            modelBuilder.Entity("Nova.Maestros.Domain.Parametro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_parametro");

                    b.Property<string>("Ambito")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ambito");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("clave");

                    b.Property<string>("CriticidadConsumo")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("criticidad_consumo");

                    b.Property<bool>("EsImpactoNegocio")
                        .HasColumnType("bit")
                        .HasColumnName("es_impacto_negocio");

                    b.Property<string>("Flujo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("flujo");

                    b.Property<string>("IdAmbito")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("id_ambito");

                    b.Property<string>("IdEmpresa")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("id_empresa");

                    b.Property<string>("Justificacion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("justificacion");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("modulo");

                    b.Property<string>("Nivel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("nivel");

                    b.Property<string>("NombreParametro")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("nombre_parametro");

                    b.Property<string>("TipoDato")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("tipo_dato");

                    b.Property<string>("Unidad")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("unidad");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("valor");

                    b.Property<DateOnly>("VigenciaDesde")
                        .HasColumnType("date")
                        .HasColumnName("vigencia_desde");

                    b.Property<DateOnly?>("VigenciaHasta")
                        .HasColumnType("date")
                        .HasColumnName("vigencia_hasta");

                    b.HasKey("Id");

                    b.HasIndex("Clave", "IdEmpresa", "IdAmbito", "VigenciaDesde")
                        .HasDatabaseName("idx_parametro_clave_ambito_vigencia");

                    b.ToTable("parametro", "maes");
                });

            modelBuilder.Entity("Nova.Maestros.Domain.Permiso", b =>
                {
                    b.Property<string>("Clave")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("clave");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("accion");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("modulo");

                    b.HasKey("Clave");

                    b.ToTable("permiso", "maes");
                });

            modelBuilder.Entity("Nova.Maestros.Domain.Puesto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_puesto");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("codigo");

                    b.Property<bool>("GeneraRatiosSenior")
                        .HasColumnType("bit")
                        .HasColumnName("genera_ratios_senior");

                    b.Property<bool>("HabilitadoSenior")
                        .HasColumnType("bit")
                        .HasColumnName("habilitado_senior");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("nombre");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("origen");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("uk_puesto_codigo");

                    b.ToTable("puesto", "maes");
                });

            modelBuilder.Entity("Nova.Maestros.Domain.Rol", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("id_rol");

                    b.Property<string>("AmbitoPermitido")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ambito_permitido");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("estado");

                    b.Property<int>("NivelAutoridad")
                        .HasColumnType("int")
                        .HasColumnName("nivel_autoridad");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("nombre");

                    b.HasKey("Codigo");

                    b.ToTable("rol", "maes");
                });

            modelBuilder.Entity("Nova.Maestros.Domain.RolPermiso", b =>
                {
                    b.Property<string>("IdRol")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("id_rol");

                    b.Property<string>("ClavePermiso")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("clave_permiso");

                    b.HasKey("IdRol", "ClavePermiso");

                    b.HasIndex("ClavePermiso");

                    b.ToTable("rol_permiso", "maes");
                });

            modelBuilder.Entity("Nova.Maestros.Domain.SemanaCampania", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_semana");

                    b.Property<DateOnly>("Desde")
                        .HasColumnType("date")
                        .HasColumnName("desde");

                    b.Property<DateOnly>("Hasta")
                        .HasColumnType("date")
                        .HasColumnName("hasta");

                    b.Property<string>("IdEmpresa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("id_empresa");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa", "Desde")
                        .HasDatabaseName("idx_campania_empresa_desde");

                    b.ToTable("semana_campania", "maes");
                });

            modelBuilder.Entity("Nova.Maestros.Domain.Tienda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_tienda");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("codigo");

                    b.Property<int>("DotacionMinimaAsesores")
                        .HasColumnType("int")
                        .HasColumnName("dotacion_minima_asesores");

                    b.Property<string>("EstadoOperativo")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("estado_operativo");

                    b.Property<DateOnly?>("FechaVigenciaDotacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_vigencia_dotacion");

                    b.Property<string>("IdEmpresa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("id_empresa");

                    b.Property<Guid?>("IdZona")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_zona");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("nombre");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("origen");

                    b.Property<DateTimeOffset?>("RmsSyncAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("rms_sync_at");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("ubicacion");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("uk_tienda_codigo");

                    b.HasIndex("IdEmpresa", "EstadoOperativo")
                        .HasDatabaseName("idx_tienda_empresa_estado");

                    b.ToTable("tienda", "maes");
                });

            modelBuilder.Entity("Nova.Maestros.Domain.Zona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_zona");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("estado");

                    b.Property<string>("IdEmpresa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("id_empresa");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa")
                        .HasDatabaseName("idx_zona_empresa");

                    b.ToTable("zona", "maes");
                });

            modelBuilder.Entity("Nova.Maestros.Domain.AmbitoFeriado", b =>
                {
                    b.HasOne("Nova.Maestros.Domain.Feriado", null)
                        .WithMany("Ambitos")
                        .HasForeignKey("IdFeriado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nova.Maestros.Domain.RolPermiso", b =>
                {
                    b.HasOne("Nova.Maestros.Domain.Permiso", null)
                        .WithMany()
                        .HasForeignKey("ClavePermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nova.Maestros.Domain.Rol", null)
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nova.Maestros.Domain.Feriado", b =>
                {
                    b.Navigation("Ambitos");
                });
#pragma warning restore 612, 618
        }
    }
}
