// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nova.Seguridad.Infrastructure;

#nullable disable

namespace Nova.Seguridad.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SeguridadDbContext))]
    [Migration("20260610205151_InitSeguridad")]
    partial class InitSeguridad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("segu")
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nova.Seguridad.Domain.Credencial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_credencial");

                    b.Property<string>("Algoritmo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("algoritmo");

                    b.Property<DateTimeOffset?>("BloqueadoHasta")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("bloqueado_hasta");

                    b.Property<DateTimeOffset>("FechaUltimoCambio")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("fecha_ultimo_cambio");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("hash_password");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_usuario");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("int")
                        .HasColumnName("intentos_fallidos");

                    b.Property<bool>("RequiereCambio")
                        .HasColumnType("bit")
                        .HasColumnName("requiere_cambio");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario")
                        .IsUnique()
                        .HasDatabaseName("uk_credencial_usuario");

                    b.ToTable("credencial", "segu");
                });

            modelBuilder.Entity("Nova.Seguridad.Domain.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_usuario");

                    b.Property<string>("CodigoEmpleadoRms")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("codigo_empleado_rms");

                    b.Property<string>("CorreoContacto")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("correo_contacto")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AI");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("FechaAlta")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("fecha_alta");

                    b.Property<DateTimeOffset?>("FechaBaja")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("fecha_baja");

                    b.Property<string>("MetodoAutenticacion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("metodo_autenticacion");

                    b.Property<bool>("MfaHabilitado")
                        .HasColumnType("bit")
                        .HasColumnName("mfa_habilitado");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("nombre_usuario")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AI");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tipo_usuario");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique()
                        .HasDatabaseName("uk_usuario_nombre");

                    b.ToTable("usuario", "segu");
                });

            modelBuilder.Entity("Nova.Seguridad.Domain.Credencial", b =>
                {
                    b.HasOne("Nova.Seguridad.Domain.Usuario", null)
                        .WithOne()
                        .HasForeignKey("Nova.Seguridad.Domain.Credencial", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
