// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nova.Rol.Infrastructure;

#nullable disable

namespace Nova.Rol.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RolDbContext))]
    [Migration("20260610230352_InitRol")]
    partial class InitRol
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("rol")
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nova.Rol.Domain.HistorialCambioRol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_historial");

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comentario");

                    b.Property<string>("EstadoAnterior")
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)")
                        .HasColumnName("estado_anterior");

                    b.Property<string>("EstadoNuevo")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("estado_nuevo");

                    b.Property<DateTimeOffset>("FechaEvento")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("fecha_evento");

                    b.Property<Guid?>("ProgramacionDiaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_programacion");

                    b.Property<Guid>("RolSemanalId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_rol");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tipo_evento");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id");

                    b.HasIndex("RolSemanalId", "FechaEvento")
                        .HasDatabaseName("idx_historial_rol_fecha");

                    b.ToTable("historial_cambio_rol", "rol");
                });

            modelBuilder.Entity("Nova.Rol.Domain.ProgramacionDia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_programacion");

                    b.Property<Guid>("ColaboradorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_colaborador");

                    b.Property<Guid?>("ConceptoCompensacionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_concepto_compensacion");

                    b.Property<bool>("EsSugerenciaSistema")
                        .HasColumnType("bit")
                        .HasColumnName("es_sugerencia_sistema");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<DateTimeOffset>("FechaRegistro")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("fecha_registro");

                    b.Property<Guid>("RegistradoPor")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("registrado_por");

                    b.Property<Guid>("RolSemanalId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_rol");

                    b.Property<Guid?>("TiendaCoberturaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_tienda_cobertura");

                    b.Property<string>("TipoVenta")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("tipo_venta");

                    b.HasKey("Id");

                    b.HasIndex("RolSemanalId", "ColaboradorId", "Fecha")
                        .IsUnique()
                        .HasDatabaseName("uk_programacion_colaborador_fecha");

                    b.ToTable("programacion_dia", "rol");
                });

            modelBuilder.Entity("Nova.Rol.Domain.RolSemanal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_rol");

                    b.Property<int>("Anio")
                        .HasColumnType("int")
                        .HasColumnName("anio");

                    b.Property<Guid?>("AprobadoPorGg")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("aprobado_por_gg");

                    b.Property<Guid>("CreadoPor")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("creado_por");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("empresa");

                    b.Property<Guid?>("EnviadoPorGz")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("enviado_por_gz");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset?>("FechaAprobacionGg")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("fecha_aprobacion_gg");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTimeOffset?>("FechaEnvioGz")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("fecha_envio_gz");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<DateTimeOffset?>("FechaProgramacionGt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("fecha_programacion_gt");

                    b.Property<int>("NumeroSemana")
                        .HasColumnType("int")
                        .HasColumnName("numero_semana");

                    b.Property<Guid?>("ProgramadoPorGt")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("programado_por_gt");

                    b.Property<string>("Puesto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("puesto");

                    b.Property<Guid?>("TiendaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_tienda");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.Property<Guid?>("VersionVigenteId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_version_vigente");

                    b.Property<Guid>("ZonaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_zona");

                    b.HasKey("Id");

                    b.HasIndex("Empresa", "ZonaId", "Anio", "NumeroSemana", "Puesto")
                        .HasDatabaseName("idx_rol_semana");

                    b.ToTable("rol_semanal", "rol");
                });

            modelBuilder.Entity("Nova.Rol.Domain.ProgramacionDia", b =>
                {
                    b.HasOne("Nova.Rol.Domain.RolSemanal", null)
                        .WithMany("Dias")
                        .HasForeignKey("RolSemanalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nova.Rol.Domain.RolSemanal", b =>
                {
                    b.Navigation("Dias");
                });
#pragma warning restore 612, 618
        }
    }
}
