// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nova.Seguridad.Infrastructure;

#nullable disable

namespace Nova.Seguridad.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SeguridadDbContext))]
    [Migration("20260610214938_AddJerarquiaDelegacionSuplencia")]
    partial class AddJerarquiaDelegacionSuplencia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("segu")
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nova.Seguridad.Domain.AsignacionRolAmbito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_asignacion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("estado");

                    b.Property<string>("IdEmpresa")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("id_empresa");

                    b.Property<string>("IdRol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("id_rol");

                    b.Property<Guid?>("IdTienda")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_tienda");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Justificacion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("justificacion");

                    b.Property<string>("TipoAmbito")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("tipo_ambito");

                    b.Property<DateOnly>("VigenciaDesde")
                        .HasColumnType("date")
                        .HasColumnName("vigencia_desde");

                    b.Property<DateOnly?>("VigenciaHasta")
                        .HasColumnType("date")
                        .HasColumnName("vigencia_hasta");

                    b.Property<string>("_zonas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("zonas");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario", "Estado")
                        .HasDatabaseName("idx_asignacion_usuario_estado");

                    b.ToTable("asignacion_rol_ambito", "segu");
                });

            modelBuilder.Entity("Nova.Seguridad.Domain.AuditoriaSeguridad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_log");

                    b.Property<string>("Detalle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("detalle");

                    b.Property<string>("Evento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("evento");

                    b.Property<DateTimeOffset>("FechaHora")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("fecha_hora");

                    b.Property<Guid>("IdActor")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_actor");

                    b.Property<Guid?>("IdObjeto")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_objeto");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("resultado");

                    b.HasKey("Id");

                    b.HasIndex("IdActor", "FechaHora")
                        .HasDatabaseName("idx_auditoria_actor_fecha");

                    b.ToTable("auditoria_seguridad", "segu");
                });

            modelBuilder.Entity("Nova.Seguridad.Domain.CodigoOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_codigo");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("creado_en");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("ExpiraEn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("expira_en");

                    b.Property<string>("HashCodigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("hash_codigo");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_usuario");

                    b.Property<int>("Intentos")
                        .HasColumnType("int")
                        .HasColumnName("intentos");

                    b.Property<int>("MaxIntentos")
                        .HasColumnType("int")
                        .HasColumnName("max_intentos");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario", "Estado")
                        .HasDatabaseName("idx_otp_usuario_estado");

                    b.ToTable("codigo_otp", "segu");
                });

            modelBuilder.Entity("Nova.Seguridad.Domain.Credencial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_credencial");

                    b.Property<string>("Algoritmo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("algoritmo");

                    b.Property<DateTimeOffset?>("BloqueadoHasta")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("bloqueado_hasta");

                    b.Property<DateTimeOffset>("FechaUltimoCambio")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("fecha_ultimo_cambio");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("hash_password");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_usuario");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("int")
                        .HasColumnName("intentos_fallidos");

                    b.Property<bool>("RequiereCambio")
                        .HasColumnType("bit")
                        .HasColumnName("requiere_cambio");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario")
                        .IsUnique()
                        .HasDatabaseName("uk_credencial_usuario");

                    b.ToTable("credencial", "segu");
                });

            modelBuilder.Entity("Nova.Seguridad.Domain.Delegacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_delegacion");

                    b.Property<string>("Alcance")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("alcance");

                    b.Property<string>("DetalleAlcance")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("detalle_alcance");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("estado");

                    b.Property<Guid?>("IdAmbito")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_ambito");

                    b.Property<Guid>("IdDelegado")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_delegado");

                    b.Property<Guid>("IdTitular")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_titular");

                    b.Property<string>("TipoAmbito")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("tipo_ambito");

                    b.Property<DateOnly>("VigenciaDesde")
                        .HasColumnType("date")
                        .HasColumnName("vigencia_desde");

                    b.Property<DateOnly?>("VigenciaHasta")
                        .HasColumnType("date")
                        .HasColumnName("vigencia_hasta");

                    b.HasKey("Id");

                    b.HasIndex("IdDelegado", "Estado")
                        .HasDatabaseName("idx_delegacion_delegado_estado");

                    b.ToTable("delegacion", "segu");
                });

            modelBuilder.Entity("Nova.Seguridad.Domain.NodoJerarquia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_nodo");

                    b.Property<Guid?>("IdAmbito")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_ambito");

                    b.Property<Guid?>("IdNodoSuperior")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_nodo_superior");

                    b.Property<string>("IdRol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("id_rol");

                    b.Property<string>("TipoAmbito")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("tipo_ambito");

                    b.HasKey("Id");

                    b.HasIndex("IdNodoSuperior");

                    b.ToTable("nodo_jerarquia", "segu");
                });

            modelBuilder.Entity("Nova.Seguridad.Domain.Suplencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_suplencia");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("estado");

                    b.Property<Guid?>("IdAmbito")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_ambito");

                    b.Property<string>("IdRolTitular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("id_rol_titular");

                    b.Property<Guid>("IdUsuarioSuplente")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_usuario_suplente");

                    b.Property<Guid?>("IdUsuarioTitular")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_usuario_titular");

                    b.Property<string>("TipoAmbito")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("tipo_ambito");

                    b.Property<DateOnly>("VigenciaDesde")
                        .HasColumnType("date")
                        .HasColumnName("vigencia_desde");

                    b.Property<DateOnly?>("VigenciaHasta")
                        .HasColumnType("date")
                        .HasColumnName("vigencia_hasta");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuarioSuplente", "Estado")
                        .HasDatabaseName("idx_suplencia_suplente_estado");

                    b.ToTable("suplencia", "segu");
                });

            modelBuilder.Entity("Nova.Seguridad.Domain.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_usuario");

                    b.Property<string>("CodigoEmpleadoRms")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("codigo_empleado_rms");

                    b.Property<string>("CorreoContacto")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("correo_contacto")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AI");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("FechaAlta")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("fecha_alta");

                    b.Property<DateTimeOffset?>("FechaBaja")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("fecha_baja");

                    b.Property<string>("MetodoAutenticacion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("metodo_autenticacion");

                    b.Property<bool>("MfaHabilitado")
                        .HasColumnType("bit")
                        .HasColumnName("mfa_habilitado");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("nombre_usuario")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AI");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tipo_usuario");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique()
                        .HasDatabaseName("uk_usuario_nombre");

                    b.ToTable("usuario", "segu");
                });

            modelBuilder.Entity("Nova.Seguridad.Domain.AsignacionRolAmbito", b =>
                {
                    b.HasOne("Nova.Seguridad.Domain.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Nova.Seguridad.Domain.Credencial", b =>
                {
                    b.HasOne("Nova.Seguridad.Domain.Usuario", null)
                        .WithOne()
                        .HasForeignKey("Nova.Seguridad.Domain.Credencial", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nova.Seguridad.Domain.NodoJerarquia", b =>
                {
                    b.HasOne("Nova.Seguridad.Domain.NodoJerarquia", null)
                        .WithMany()
                        .HasForeignKey("IdNodoSuperior")
                        .OnDelete(DeleteBehavior.NoAction);
                });
#pragma warning restore 612, 618
        }
    }
}
